# Generated by Django 6.0 on 2026-03-31 04:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlueBookRenewal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(choices=[('two_wheeler', 'Two Wheeler'), ('two_wheeler_ev', 'Two Wheeler EV'), ('four_wheeler', 'Four Wheeler'), ('four_wheeler_ev', 'Four Wheeler EV')], max_length=20)),
                ('manufacture_year', models.IntegerField(help_text='Year of manufacture in AD')),
                ('cubic_capacity', models.IntegerField(default=0, help_text='Engine CC (0 for EV)')),
                ('last_renewal_from_bs', models.CharField(help_text='BS date e.g. 2079-01-01', max_length=20)),
                ('last_renewal_to_bs', models.CharField(help_text='BS date e.g. 2080-01-01', max_length=20)),
                ('has_third_party_insurance', models.BooleanField(default=False)),
                ('unpaid_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unpaid_tax_fine', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_current_year', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_fine_current_year', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('renewal_charge', models.DecimalField(decimal_places=2, default=300, max_digits=10)),
                ('renewal_fine', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('model_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('insurance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_charge', models.DecimalField(decimal_places=2, default=200, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('full_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('pick_location', models.TextField()),
                ('city', models.CharField(choices=[('kathmandu', 'Kathmandu'), ('lalitpur', 'Lalitpur'), ('bhaktapur', 'Bhaktapur')], max_length=20)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('staff_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blue_book_renewals', to='accounts.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='CustomerFeedback',
        ),
    ]
