# Generated by Django 6.0 on 2026-02-24 11:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField(blank=True)),
                ('amenities', models.TextField(blank=True, help_text='Comma-separated amenities: WiFi, Restroom, Cafe')),
                ('operating_hours', models.CharField(default='24/7', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Charger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('charger_name', models.CharField(max_length=100)),
                ('charger_type', models.CharField(choices=[('AC', 'AC Charger'), ('DC', 'DC Fast Charger')], max_length=2)),
                ('power_output', models.DecimalField(decimal_places=2, help_text='In kW', max_digits=5)),
                ('connector_types', models.CharField(help_text='Comma-separated: Type 2, CCS, CHAdeMO', max_length=200)),
                ('price_per_kwh', models.DecimalField(decimal_places=2, help_text='Price in NPR', max_digits=6)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance')], default='available', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chargers', to='accounts.chargingstation')),
            ],
            options={
                'ordering': ['charger_type', 'charger_name'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='accounts.charger')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('charger', 'date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_name', models.CharField(max_length=100)),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('electric', 'Electric Vehicle'), ('hybrid', 'Hybrid Vehicle')], max_length=20)),
                ('battery_capacity', models.DecimalField(decimal_places=2, help_text='In kWh', max_digits=5)),
                ('charging_port_type', models.CharField(max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='accounts.customer')),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChargingBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('estimated_energy', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated kWh', max_digits=5, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated cost in NPR', max_digits=8, null=True)),
                ('actual_energy', models.DecimalField(blank=True, decimal_places=2, help_text='Actual kWh used', max_digits=5, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Actual cost in NPR', max_digits=8, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='accounts.charger')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charging_bookings', to='accounts.customer')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='accounts.timeslot')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='accounts.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
