# Generated by Django 6.0 on 2026-04-07 08:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notification_fcmtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bluebookrenewal',
            name='cubic_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bluebookrenewal',
            name='last_renewal_from_bs',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bluebookrenewal',
            name='last_renewal_to_bs',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bluebookrenewal',
            name='manufacture_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chargingbooking',
            name='actual_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='chargingbooking',
            name='actual_energy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='chargingbooking',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='chargingbooking',
            name='estimated_energy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='amenities',
            field=models.TextField(blank=True, help_text='Comma-separated: WiFi, Restroom, Cafe'),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='specialization',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration_minutes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='preferred_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='staff_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='battery_health',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='issues_found',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='recommendations',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
