# Generated by Django 6.0 on 2026-03-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_service_servicecategory_mechanic_servicebooking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='battery_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='In kWh (EV/Hybrid only)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='charging_port_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('electric', 'Electric Vehicle'), ('hybrid', 'Hybrid Vehicle'), ('ice', 'Internal Combustion Engine')], max_length=20),
        ),
    ]
