# Generated by Django 6.0 on 2026-04-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_bluebookrenewal_cubic_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bluebookrenewal',
            name='citizenship_back',
            field=models.ImageField(blank=True, null=True, upload_to='bluebook/citizenship/'),
        ),
        migrations.AddField(
            model_name='bluebookrenewal',
            name='citizenship_front',
            field=models.ImageField(blank=True, null=True, upload_to='bluebook/citizenship/'),
        ),
        migrations.AddField(
            model_name='bluebookrenewal',
            name='insurance_doc',
            field=models.ImageField(blank=True, null=True, upload_to='bluebook/insurance/'),
        ),
    ]
