# Generated by Django 6.0 on 2026-04-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_bluebookrenewal_citizenship_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bluebookrenewal',
            name='battery_kw',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bluebookrenewal',
            name='battery_watt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
